language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
  - xbuild CI.proj | tee >&2 | grep -q "0 Error(s)"
  - nunit-console ./LikeZelda.Tests/bin/Debug/LikeZeldaTests.dll